In [27]:
import torch

In [28]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [29]:
x.requires_grad_(True) #存储grad
x.grad

In [30]:
#计算函数 y = 2* xTx
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [31]:
#调用Backward得到y对于x的梯度
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [34]:
#测试
x.grad == 4*x

tensor([True, True, True, True])

In [39]:
#在默认情况, Pytorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
#算另外一个函数 y=x1+x2+...+xn, dy/dx = 1,1,...,1
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.], grad_fn=<ZeroBackward0>)

In [42]:
#对非标量调用backward，需要传入一个grad参数，该参数指定微分函数
x.grad.zero_()
#在深度学习中，很少对张量求导
y = x * x 
#转化为标量后求导
y.sum().backward()
x.grad


tensor([0., 2., 4., 6.], grad_fn=<ZeroBackward0>)

In [43]:
#将一些计算移动到记录的计算图之外
x.grad.zero_()
y = x * x
# detach()是将u变为一个常数，不再是一个关于x的函数
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [49]:
#不影响y的计算
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [55]:
#当构建函数需要控制流（例如条件，循环等），我们仍然可以计算梯度
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum()>0:
        c = b
    else:
        c = 100 * b
    return c
#随机数，size=()是标量
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

a.grad == d/a

tensor(True)